### ISSUE TITLE
[Web Bug] - Providers

### ISSUE THREAD

**Issue by cjuega** [crossplane/crossplane.github.io#946]
URL: https://docs.crossplane.io/v1.20/concepts/providers/#configuring-metadata-of-runtime-resources

The note about `serviceAccountTemplate` and the alternative for using an existing service account is misleading. It's not enough to define the `deploymentTemplate.spec.template.spec.serviceAccountName` property because there are some mandatory fields in that schema.

It would be nice to add an example to prevent the trial-error process. Here is a minimum working example to set an existing service account:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: name-of-the-drc
spec:
  deploymentTemplate:
    spec:
      selector: {}       # selector must be defined as it's required by the schema
      template:
        spec:
          containers: [] # containers must be defined as it's required by the schema
          serviceAccountName: name-of-an-existing-sa
```
